# Generated by Django 5.0.4 on 2024-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='unit',
            new_name='tenant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='square_feet',
        ),
    ]
