# Generated by Django 4.2.15 on 2024-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_unit_charge_tenant_remove_payment_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
