# Generated by Django 4.2.15 on 2024-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_charge_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord'), ('Property Manager', 'Property Manager')], default='Tenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='charge',
            name='paid',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
