# Generated by Django 4.2.15 on 2024-09-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_rename_paid_charge_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='type',
            new_name='role',
        ),
    ]
