# Generated by Django 4.2.18 on 2025-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_rename_type_tenant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('bank_account', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('bank_id', models.CharField(max_length=255)),
            ],
        ),
    ]
